example.property: "I am demomic license DEFAULT config"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/demomic_license
    username: GZ_DEMOMIC
    password: GZ_DEMOMIC