demomic-license:
  greetingMessage: "Greeting message from demomic license DEV"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DEMOMIC_LICENSE
    username: DEMOMIC_LICENSE
    password: DEMOMIC_LICENSE