demomic-product:
  greetingMessage: "Greeting message from demomic product"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DEMOMIC_PRODUCT
    username: "DEMOMIC_PRODUCT"
    password: "DEMOMIC_PRODUCT"
